### ISSUE TITLE
build on ubuntu 20.04

### ISSUE THREAD

**Issue by MrCoolSpan** [rofl0r/openbor#2]
hello
I'm hoping that you can help me compile on Ubuntu 20.04
i got i working on Ubuntu 18 with this
sed -i 's/-fsigned-char/-fsigned-char -fasm -g -no-pie /g' Makefile

But on 20.04 i cant get it to work
i get a lot of multiple definition of `sprite
i really hope you can find the time to help me

**Comment by rofl0r** [comment]
thanks for your report. there was indeed a bug preventing compilation on ubuntu 20.04 from working, as its libc is compiled with -fPIE. this helped uncover the bug i just fixed in this commit:  https://github.com/rofl0r/openbor/commit/4f377896d29b69ba8dce840155476f290640c975

please try again, without your sed hack (and run make clean afterwards). it compiled for me just fine.

**Comment by MrCoolSpan** [comment]
No it not working
```
gned-char -fno-ident -freorder-blocks -DSDL -DOV_EXCLUDE_STATIC_CALLBACKS -DOPENGL -DLOADGL -c source/preprocessorlib/pp_parser.c -o source/preprocessorlib/pp_parser.o
source/preprocessorlib/pp_parser.c: In function ‘pp_parser_stringify’:
source/preprocessorlib/pp_parser.c:497:5: warning: ‘strncat’ specified bound 2 equals source length [-Wstringop-overflow=]
  497 |     strncat(self->token.theSource, "\\\"", 2);
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
source/preprocessorlib/pp_parser.c:500:5: warning: ‘strncat’ specified bound 2 equals source length [-Wstringop-overflow=]
  500 |     strncat(self->token.theSource, "\\\\", 2);
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
source/preprocessorlib/pp_parser.c:511:2: warning: ‘strncat’ specified bound 1 equals source length [-Wstringop-overflow=]
  511 |  strncat(self->token.theSource, "\"", 1);
      |  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Compiling Port: source/randlib/rand32.c...
cc -DOPENGL -Isdl -I. -Isource -Isource/adpcmlib -Isource/gamelib -Isource/preprocessorlib -Isource/randlib -Isource/scriptlib -Isource/pnglib -Isource/pcxlib -Isource/gfxlib -I/include -I/include/SDL -Wall -fsigned-char -fno-ident -freorder-blocks -DSDL -DOV_EXCLUDE_STATIC_CALLBACKS -DOPENGL -DLOADGL -c source/randlib/rand32.c -o source/randlib/rand32.o
Compiling Port: source/pnglib/pngdec.c...
cc -DOPENGL -Isdl -I. -Isource -Isource/adpcmlib -Isource/gamelib -Isource/preprocessorlib -Isource/randlib -Isource/scriptlib -Isource/pnglib -Isource/pcxlib -Isource/gfxlib -I/include -I/include/SDL -Wall -fsigned-char -fno-ident -freorder-blocks -DSDL -DOV_EXCLUDE_STATIC_CALLBACKS -DOPENGL -DLOADGL -c source/pnglib/pngdec.c -o source/pnglib/pngdec.o
Compiling Port: source/pnglib/savepng.c...
cc -DOPENGL -Isdl -I. -Isource -Isource/adpcmlib -Isource/gamelib -Isource/preprocessorlib -Isource/randlib -Isource/scriptlib -Isource/pnglib -Isource/pcxlib -Isource/gfxlib -I/include -I/include/SDL -Wall -fsigned-char -fno-ident -freorder-blocks -DSDL -DOV_EXCLUDE_STATIC_CALLBACKS -DOPENGL -DLOADGL -c source/pnglib/savepng.c -o source/pnglib/savepng.o

Linking Port: OpenBOR...
cc -DOPENGL -Isdl -I. -Isource -Isource/adpcmlib -Isource/gamelib -Isource/preprocessorlib -Isource/randlib -Isource/scriptlib -Isource/pnglib -Isource/pcxlib -Isource/gfxlib -I/include -I/include/SDL -Wall -fsigned-char -fno-ident -freorder-blocks -DSDL -DOV_EXCLUDE_STATIC_CALLBACKS -DOPENGL -DLOADGL -o OpenBOR openbor.o data.o openborscript.o sdl/joysticks.o sdl/control.o sdl/sblaster.o sdl/timer.o sdl/sdlport.o sdl/video.o sdl/menu.o sdl/opengl.o sdl/loadgl.o source/adpcmlib/adpcm.o source/gfxlib/2xSaI.o source/gfxlib/bilinear.o source/gfxlib/dotmatrix.o source/gfxlib/gfx.o source/gfxlib/hq2x.o source/gfxlib/motionblur.o source/gfxlib/scale2x.o source/gfxlib/scanline.o source/gfxlib/simple2x.o source/gfxlib/tv2x.o source/gamelib/draw.o source/gamelib/draw16.o source/gamelib/draw32.o source/gamelib/font.o source/gamelib/anigif.o source/gamelib/bitmap.o source/gamelib/screen.o source/gamelib/screen16.o source/gamelib/screen32.o source/gamelib/loadimg.o source/gamelib/palette.o source/gamelib/packfile.o source/gamelib/filecache.o source/gamelib/pixelformat.o source/gamelib/soundmix.o source/gamelib/spritef.o source/gamelib/spriteq.o source/gamelib/spritex8p16.o source/gamelib/spritex8p32.o source/gamelib/texture.o source/gamelib/texture16.o source/gamelib/commands.o source/gamelib/models.o source/gamelib/texture32.o source/gamelib/movie.o source/gamelib/menus.o source/gamelib/filters.o source/stringptr.o source/utils.o source/stristr.o source/scriptlib/StackedSymbolTable.o source/scriptlib/ScriptVariant.o source/scriptlib/SymbolTable.o source/scriptlib/Instruction.o source/scriptlib/Interpreter.o source/scriptlib/ImportCache.o source/scriptlib/ParserSet.o source/scriptlib/Parser.o source/scriptlib/Lexer.o source/scriptlib/Stack.o source/scriptlib/List.o source/scriptlib/SolidList.o source/preprocessorlib/pp_lexer.o source/preprocessorlib/pp_parser.o source/randlib/rand32.o source/pnglib/pngdec.o source/pnglib/savepng.o -lSDL -lSDL_gfx -lpthread -lvorbisfile -lvorbis -logg -lpng -lz -lm
/usr/bin/ld: data.o:(.bss+0x0): multiple definition of `sprite_list'; openbor.o:(.bss+0x0): first defined here
/usr/bin/ld: data.o:(.bss+0x8): multiple definition of `sprite_map'; openbor.o:(.bss+0x8): first defined here
/usr/bin/ld: data.o:(.bss+0x20): multiple definition of `joysticks'; openbor.o:(.bss+0x20): first defined here
/usr/bin/ld: data.o:(.bss+0x4e0): multiple definition of `anim_list'; openbor.o:(.bss+0x4e0): first defined here
/usr/bin/ld: data.o:(.bss+0x4e8): multiple definition of `model_cache'; openbor.o:(.bss+0x4e8): first defined here
/usr/bin/ld: openborscript.o:(.bss+0x0): multiple definition of `sprite_list'; openbor.o:(.bss+0x0): first defined here
/usr/bin/ld: openborscript.o:(.bss+0x8): multiple definition of `sprite_map'; openbor.o:(.bss+0x8): first defined here
/usr/bin/ld: openborscript.o:(.bss+0x20): multiple definition of `joysticks'; openbor.o:(.bss+0x20): first defined here
/usr/bin/ld: openborscript.o:(.bss+0x4e0): multiple definition of `anim_list'; openbor.o:(.bss+0x4e0): first defined here
/usr/bin/ld: openborscript.o:(.bss+0x4e8): multiple definition of `model_cache'; openbor.o:(.bss+0x4e8): first defined here
/usr/bin/ld: sdl/joysticks.o:(.bss+0x0): multiple definition of `joysticks'; openbor.o:(.bss+0x20): first defined here
/usr/bin/ld: sdl/control.o:(.bss+0x0): multiple definition of `sprite_list'; openbor.o:(.bss+0x0): first defined here
/usr/bin/ld: sdl/control.o:(.bss+0x8): multiple definition of `sprite_map'; openbor.o:(.bss+0x8): first defined here
/usr/bin/ld: sdl/control.o:(.bss+0x20): multiple definition of `joysticks'; openbor.o:(.bss+0x20): first defined here
/usr/bin/ld: sdl/control.o:(.bss+0x4e0): multiple definition of `anim_list'; openbor.o:(.bss+0x4e0): first defined here
/usr/bin/ld: sdl/control.o:(.bss+0x4e8): multiple definition of `model_cache'; openbor.o:(.bss+0x4e8): first defined here
/usr/bin/ld: sdl/sblaster.o:(.bss+0x0): multiple definition of `sprite_list'; openbor.o:(.bss+0x0): first defined here
/usr/bin/ld: sdl/sblaster.o:(.bss+0x8): multiple definition of `sprite_map'; openbor.o:(.bss+0x8): first defined here
/usr/bin/ld: sdl/sdlport.o:(.bss+0x0): multiple definition of `sprite_list'; openbor.o:(.bss+0x0): first defined here
/usr/bin/ld: sdl/sdlport.o:(.bss+0x8): multiple definition of `sprite_map'; openbor.o:(.bss+0x8): first defined here
/usr/bin/ld: sdl/video.o:(.bss+0x0): multiple definition of `sprite_list'; openbor.o:(.bss+0x0): first defined here
/usr/bin/ld: sdl/video.o:(.bss+0x8): multiple definition of `sprite_map'; openbor.o:(.bss+0x8): first defined here
/usr/bin/ld: sdl/video.o:(.bss+0x20): multiple definition of `joysticks'; openbor.o:(.bss+0x20): first defined here
/usr/bin/ld: sdl/video.o:(.bss+0x4e0): multiple definition of `anim_list'; openbor.o:(.bss+0x4e0): first defined here
/usr/bin/ld: sdl/video.o:(.bss+0x4e8): multiple definition of `model_cache'; openbor.o:(.bss+0x4e8): first defined here
/usr/bin/ld: sdl/menu.o:(.bss+0x0): multiple definition of `sprite_list'; openbor.o:(.bss+0x0): first defined here
/usr/bin/ld: sdl/menu.o:(.bss+0x8): multiple definition of `sprite_map'; openbor.o:(.bss+0x8): first defined here
/usr/bin/ld: sdl/menu.o:(.bss+0x20): multiple definition of `joysticks'; openbor.o:(.bss+0x20): first defined here
/usr/bin/ld: sdl/menu.o:(.bss+0x4e0): multiple definition of `anim_list'; openbor.o:(.bss+0x4e0): first defined here
/usr/bin/ld: sdl/menu.o:(.bss+0x4e8): multiple definition of `model_cache'; openbor.o:(.bss+0x4e8): first defined here
/usr/bin/ld: sdl/opengl.o:(.bss+0x0): multiple definition of `sprite_list'; openbor.o:(.bss+0x0): first defined here
/usr/bin/ld: sdl/opengl.o:(.bss+0x8): multiple definition of `sprite_map'; openbor.o:(.bss+0x8): first defined here
/usr/bin/ld: sdl/opengl.o:(.bss+0x20): multiple definition of `joysticks'; openbor.o:(.bss+0x20): first defined here
/usr/bin/ld: sdl/opengl.o:(.bss+0x4e0): multiple definition of `anim_list'; openbor.o:(.bss+0x4e0): first defined here
/usr/bin/ld: sdl/opengl.o:(.bss+0x4e8): multiple definition of `model_cache'; openbor.o:(.bss+0x4e8): first defined here
/usr/bin/ld: sdl/loadgl.o:(.bss+0x0): multiple definition of `sprite_list'; openbor.o:(.bss+0x0): first defined here
/usr/bin/ld: sdl/loadgl.o:(.bss+0x8): multiple definition of `sprite_map'; openbor.o:(.bss+0x8): first defined here
/usr/bin/ld: source/gfxlib/2xSaI.o:(.bss+0x0): multiple definition of `sprite_list'; openbor.o:(.bss+0x0): first defined here
/usr/bin/ld: source/gfxlib/2xSaI.o:(.bss+0x8): multiple definition of `sprite_map'; openbor.o:(.bss+0x8): first defined here
/usr/bin/ld: source/gfxlib/bilinear.o:(.bss+0x0): multiple definition of `sprite_list'; openbor.o:(.bss+0x0): first defined here
/usr/bin/ld: source/gfxlib/bilinear.o:(.bss+0x8): multiple definition of `sprite_map'; openbor.o:(.bss+0x8): first defined here
/usr/bin/ld: source/gfxlib/dotmatrix.o:(.bss+0x0): multiple definition of `sprite_list'; openbor.o:(.bss+0x0): first defined here
/usr/bin/ld: source/gfxlib/dotmatrix.o:(.bss+0x8): multiple definition of `sprite_map'; openbor.o:(.bss+0x8): first defined here
/usr/bin/ld: source/gfxlib/gfx.o:(.bss+0x0): multiple definition of `sprite_list'; openbor.o:(.bss+0x0): first defined here
/usr/bin/ld: source/gfxlib/gfx.o:(.bss+0x8): multiple definition of `sprite_map'; openbor.o:(.bss+0x8): first defined here
/usr/bin/ld: source/gfxlib/hq2x.o:(.bss+0x0): multiple definition of `sprite_list'; openbor.o:(.bss+0x0): first defined here
/usr/bin/ld: source/gfxlib/hq2x.o:(.bss+0x8): multiple definition of `sprite_map'; openbor.o:(.bss+0x8): first defined here
/usr/bin/ld: source/gfxlib/motionblur.o:(.bss+0x0): multiple definition of `sprite_list'; openbor.o:(.bss+0x0): first defined here
/usr/bin/ld: source/gfxlib/motionblur.o:(.bss+0x8): multiple definition of `sprite_map'; openbor.o:(.bss+0x8): first defined here
/usr/bin/ld: source/gfxlib/scale2x.o:(.bss+0x0): multiple definition of `sprite_list'; openbor.o:(.bss+0x0): first defined here
/usr/bin/ld: source/gfxlib/scale2x.o:(.bss+0x8): multiple definition of `sprite_map'; openbor.o:(.bss+0x8): first defined here
/usr/bin/ld: source/gfxlib/scanline.o:(.bss+0x0): multiple definition of `sprite_list'; openbor.o:(.bss+0x0): first defined here
/usr/bin/ld: source/gfxlib/scanline.o:(.bss+0x8): multiple definition of `sprite_map'; openbor.o:(.bss+0x8): first defined here
/usr/bin/ld: source/gfxlib/simple2x.o:(.bss+0x0): multiple definition of `sprite_list'; openbor.o:(.bss+0x0): first defined here
/usr/bin/ld: source/gfxlib/simple2x.o:(.bss+0x8): multiple definition of `sprite_map'; openbor.o:(.bss+0x8): first defined here
/usr/bin/ld: source/gfxlib/tv2x.o:(.bss+0x0): multiple definition of `sprite_list'; openbor.o:(.bss+0x0): first defined here
/usr/bin/ld: source/gfxlib/tv2x.o:(.bss+0x8): multiple definition of `sprite_map'; openbor.o:(.bss+0x8): first defined here
/usr/bin/ld: source/gamelib/draw.o:(.bss+0x0): multiple definition of `sprite_list'; openbor.o:(.bss+0x0): first defined here
/usr/bin/ld: source/gamelib/draw.o:(.bss+0x8): multiple definition of `sprite_map'; openbor.o:(.bss+0x8): first defined here
/usr/bin/ld: source/gamelib/draw16.o:(.bss+0x0): multiple definition of `sprite_list'; openbor.o:(.bss+0x0): first defined here
/usr/bin/ld: source/gamelib/draw16.o:(.bss+0x8): multiple definition of `sprite_map'; openbor.o:(.bss+0x8): first defined here
/usr/bin/ld: source/gamelib/draw32.o:(.bss+0x0): multiple definition of `sprite_list'; openbor.o:(.bss+0x0): first defined here
/usr/bin/ld: source/gamelib/draw32.o:(.bss+0x8): multiple definition of `sprite_map'; openbor.o:(.bss+0x8): first defined here
/usr/bin/ld: source/gamelib/font.o:(.bss+0x0): multiple definition of `sprite_list'; openbor.o:(.bss+0x0): first defined here
/usr/bin/ld: source/gamelib/font.o:(.bss+0x8): multiple definition of `sprite_map'; openbor.o:(.bss+0x8): first defined here
/usr/bin/ld: source/gamelib/anigif.o:(.bss+0x0): multiple definition of `sprite_list'; openbor.o:(.bss+0x0): first defined here
/usr/bin/ld: source/gamelib/anigif.o:(.bss+0x8): multiple definition of `sprite_map'; openbor.o:(.bss+0x8): first defined here
/usr/bin/ld: source/gamelib/bitmap.o:(.bss+0x0): multiple definition of `sprite_list'; openbor.o:(.bss+0x0): first defined here
/usr/bin/ld: source/gamelib/bitmap.o:(.bss+0x8): multiple definition of `sprite_map'; openbor.o:(.bss+0x8): first defined here
/usr/bin/ld: source/gamelib/screen.o:(.bss+0x0): multiple definition of `sprite_list'; openbor.o:(.bss+0x0): first defined here
/usr/bin/ld: source/gamelib/screen.o:(.bss+0x8): multiple definition of `sprite_map'; openbor.o:(.bss+0x8): first defined here
/usr/bin/ld: source/gamelib/screen16.o:(.bss+0x0): multiple definition of `sprite_list'; openbor.o:(.bss+0x0): first defined here
/usr/bin/ld: source/gamelib/screen16.o:(.bss+0x8): multiple definition of `sprite_map'; openbor.o:(.bss+0x8): first defined here
/usr/bin/ld: source/gamelib/screen32.o:(.bss+0x0): multiple definition of `sprite_list'; openbor.o:(.bss+0x0): first defined here
/usr/bin/ld: source/gamelib/screen32.o:(.bss+0x8): multiple definition of `sprite_map'; openbor.o:(.bss+0x8): first defined here
/usr/bin/ld: source/gamelib/loadimg.o:(.bss+0x0): multiple definition of `sprite_list'; openbor.o:(.bss+0x0): first defined here
/usr/bin/ld: source/gamelib/loadimg.o:(.bss+0x8): multiple definition of `sprite_map'; openbor.o:(.bss+0x8): first defined here
/usr/bin/ld: source/gamelib/palette.o:(.bss+0x0): multiple definition of `sprite_list'; openbor.o:(.bss+0x0): first defined here
/usr/bin/ld: source/gamelib/palette.o:(.bss+0x8): multiple definition of `sprite_map'; openbor.o:(.bss+0x8): first defined here
/usr/bin/ld: source/gamelib/packfile.o:(.bss+0x0): multiple definition of `sprite_list'; openbor.o:(.bss+0x0): first defined here
/usr/bin/ld: source/gamelib/packfile.o:(.bss+0x8): multiple definition of `sprite_map'; openbor.o:(.bss+0x8): first defined here
/usr/bin/ld: source/gamelib/packfile.o:(.bss+0x20): multiple definition of `joysticks'; openbor.o:(.bss+0x20): first defined here
/usr/bin/ld: source/gamelib/packfile.o:(.bss+0x4e0): multiple definition of `anim_list'; openbor.o:(.bss+0x4e0): first defined here
/usr/bin/ld: source/gamelib/packfile.o:(.bss+0x4e8): multiple definition of `model_cache'; openbor.o:(.bss+0x4e8): first defined here
/usr/bin/ld: source/gamelib/filecache.o:(.bss+0x0): multiple definition of `sprite_list'; openbor.o:(.bss+0x0): first defined here
/usr/bin/ld: source/gamelib/filecache.o:(.bss+0x8): multiple definition of `sprite_map'; openbor.o:(.bss+0x8): first defined here
/usr/bin/ld: source/gamelib/filecache.o:(.bss+0x20): multiple definition of `joysticks'; openbor.o:(.bss+0x20): first defined here
/usr/bin/ld: source/gamelib/filecache.o:(.bss+0x4e0): multiple definition of `anim_list'; openbor.o:(.bss+0x4e0): first defined here
/usr/bin/ld: source/gamelib/filecache.o:(.bss+0x4e8): multiple definition of `model_cache'; openbor.o:(.bss+0x4e8): first defined here
/usr/bin/ld: source/gamelib/pixelformat.o:(.bss+0x0): multiple definition of `sprite_list'; openbor.o:(.bss+0x0): first defined here
/usr/bin/ld: source/gamelib/pixelformat.o:(.bss+0x8): multiple definition of `sprite_map'; openbor.o:(.bss+0x8): first defined here
/usr/bin/ld: source/gamelib/soundmix.o:(.bss+0x0): multiple definition of `sprite_list'; openbor.o:(.bss+0x0): first defined here
/usr/bin/ld: source/gamelib/soundmix.o:(.bss+0x8): multiple definition of `sprite_map'; openbor.o:(.bss+0x8): first defined here
/usr/bin/ld: source/gamelib/spritef.o:(.bss+0x0): multiple definition of `sprite_list'; openbor.o:(.bss+0x0): first defined here
/usr/bin/ld: source/gamelib/spritef.o:(.bss+0x8): multiple definition of `sprite_map'; openbor.o:(.bss+0x8): first defined here
/usr/bin/ld: source/gamelib/spriteq.o:(.bss+0x0): multiple definition of `sprite_list'; openbor.o:(.bss+0x0): first defined here
/usr/bin/ld: source/gamelib/spriteq.o:(.bss+0x8): multiple definition of `sprite_map'; openbor.o:(.bss+0x8): first defined here
/usr/bin/ld: source/gamelib/spritex8p16.o:(.bss+0x0): multiple definition of `sprite_list'; openbor.o:(.bss+0x0): first defined here
/usr/bin/ld: source/gamelib/spritex8p16.o:(.bss+0x8): multiple definition of `sprite_map'; openbor.o:(.bss+0x8): first defined here
/usr/bin/ld: source/gamelib/spritex8p32.o:(.bss+0x0): multiple definition of `sprite_list'; openbor.o:(.bss+0x0): first defined here
/usr/bin/ld: source/gamelib/spritex8p32.o:(.bss+0x8): multiple definition of `sprite_map'; openbor.o:(.bss+0x8): first defined here
/usr/bin/ld: source/gamelib/texture.o:(.bss+0x0): multiple definition of `sprite_list'; openbor.o:(.bss+0x0): first defined here
/usr/bin/ld: source/gamelib/texture.o:(.bss+0x8): multiple definition of `sprite_map'; openbor.o:(.bss+0x8): first defined here
/usr/bin/ld: source/gamelib/texture16.o:(.bss+0x0): multiple definition of `sprite_list'; openbor.o:(.bss+0x0): first defined here
/usr/bin/ld: source/gamelib/texture16.o:(.bss+0x8): multiple definition of `sprite_map'; openbor.o:(.bss+0x8): first defined here
/usr/bin/ld: source/gamelib/commands.o:(.bss+0x0): multiple definition of `sprite_list'; openbor.o:(.bss+0x0): first defined here
/usr/bin/ld: source/gamelib/commands.o:(.bss+0x8): multiple definition of `sprite_map'; openbor.o:(.bss+0x8): first defined here
/usr/bin/ld: source/gamelib/commands.o:(.bss+0x20): multiple definition of `joysticks'; openbor.o:(.bss+0x20): first defined here
/usr/bin/ld: source/gamelib/commands.o:(.bss+0x4e0): multiple definition of `anim_list'; openbor.o:(.bss+0x4e0): first defined here
/usr/bin/ld: source/gamelib/commands.o:(.bss+0x4e8): multiple definition of `model_cache'; openbor.o:(.bss+0x4e8): first defined here
/usr/bin/ld: source/gamelib/models.o:(.bss+0x0): multiple definition of `sprite_list'; openbor.o:(.bss+0x0): first defined here
/usr/bin/ld: source/gamelib/models.o:(.bss+0x8): multiple definition of `sprite_map'; openbor.o:(.bss+0x8): first defined here
/usr/bin/ld: source/gamelib/models.o:(.bss+0x20): multiple definition of `joysticks'; openbor.o:(.bss+0x20): first defined here
/usr/bin/ld: source/gamelib/models.o:(.bss+0x4e0): multiple definition of `anim_list'; openbor.o:(.bss+0x4e0): first defined here
/usr/bin/ld: source/gamelib/models.o:(.bss+0x4e8): multiple definition of `model_cache'; openbor.o:(.bss+0x4e8): first defined here
/usr/bin/ld: source/gamelib/texture32.o:(.bss+0x0): multiple definition of `sprite_list'; openbor.o:(.bss+0x0): first defined here
/usr/bin/ld: source/gamelib/texture32.o:(.bss+0x8): multiple definition of `sprite_map'; openbor.o:(.bss+0x8): first defined here
/usr/bin/ld: source/gamelib/movie.o:(.bss+0x0): multiple definition of `sprite_list'; openbor.o:(.bss+0x0): first defined here
/usr/bin/ld: source/gamelib/movie.o:(.bss+0x8): multiple definition of `sprite_map'; openbor.o:(.bss+0x8): first defined here
/usr/bin/ld: source/gamelib/movie.o:(.bss+0x20): multiple definition of `joysticks'; openbor.o:(.bss+0x20): first defined here
/usr/bin/ld: source/gamelib/movie.o:(.bss+0x4e0): multiple definition of `anim_list'; openbor.o:(.bss+0x4e0): first defined here
/usr/bin/ld: source/gamelib/movie.o:(.bss+0x4e8): multiple definition of `model_cache'; openbor.o:(.bss+0x4e8): first defined here
/usr/bin/ld: source/gamelib/menus.o:(.bss+0x0): multiple definition of `sprite_list'; openbor.o:(.bss+0x0): first defined here
/usr/bin/ld: source/gamelib/menus.o:(.bss+0x8): multiple definition of `sprite_map'; openbor.o:(.bss+0x8): first defined here
/usr/bin/ld: source/gamelib/menus.o:(.bss+0x20): multiple definition of `joysticks'; openbor.o:(.bss+0x20): first defined here
/usr/bin/ld: source/gamelib/menus.o:(.bss+0x4e0): multiple definition of `anim_list'; openbor.o:(.bss+0x4e0): first defined here
/usr/bin/ld: source/gamelib/menus.o:(.bss+0x4e8): multiple definition of `model_cache'; openbor.o:(.bss+0x4e8): first defined here
/usr/bin/ld: source/gamelib/filters.o:(.bss+0x0): multiple definition of `sprite_list'; openbor.o:(.bss+0x0): first defined here
/usr/bin/ld: source/gamelib/filters.o:(.bss+0x8): multiple definition of `sprite_map'; openbor.o:(.bss+0x8): first defined here
/usr/bin/ld: source/utils.o:(.bss+0x0): multiple definition of `sprite_list'; openbor.o:(.bss+0x0): first defined here
/usr/bin/ld: source/utils.o:(.bss+0x8): multiple definition of `sprite_map'; openbor.o:(.bss+0x8): first defined here
/usr/bin/ld: source/utils.o:(.bss+0x20): multiple definition of `joysticks'; openbor.o:(.bss+0x20): first defined here
/usr/bin/ld: source/utils.o:(.bss+0x4e0): multiple definition of `anim_list'; openbor.o:(.bss+0x4e0): first defined here
/usr/bin/ld: source/utils.o:(.bss+0x4e8): multiple definition of `model_cache'; openbor.o:(.bss+0x4e8): first defined here
/usr/bin/ld: source/scriptlib/StackedSymbolTable.o:(.bss+0x0): multiple definition of `sprite_list'; openbor.o:(.bss+0x0): first defined here
/usr/bin/ld: source/scriptlib/StackedSymbolTable.o:(.bss+0x8): multiple definition of `sprite_map'; openbor.o:(.bss+0x8): first defined here
/usr/bin/ld: source/scriptlib/ScriptVariant.o:(.bss+0x0): multiple definition of `sprite_list'; openbor.o:(.bss+0x0): first defined here
/usr/bin/ld: source/scriptlib/ScriptVariant.o:(.bss+0x8): multiple definition of `sprite_map'; openbor.o:(.bss+0x8): first defined here
/usr/bin/ld: source/scriptlib/SymbolTable.o:(.bss+0x0): multiple definition of `sprite_list'; openbor.o:(.bss+0x0): first defined here
/usr/bin/ld: source/scriptlib/SymbolTable.o:(.bss+0x8): multiple definition of `sprite_map'; openbor.o:(.bss+0x8): first defined here
/usr/bin/ld: source/scriptlib/Instruction.o:(.bss+0x0): multiple definition of `sprite_list'; openbor.o:(.bss+0x0): first defined here
/usr/bin/ld: source/scriptlib/Instruction.o:(.bss+0x8): multiple definition of `sprite_map'; openbor.o:(.bss+0x8): first defined here
/usr/bin/ld: source/scriptlib/Interpreter.o:(.bss+0x0): multiple definition of `sprite_list'; openbor.o:(.bss+0x0): first defined here
/usr/bin/ld: source/scriptlib/Interpreter.o:(.bss+0x8): multiple definition of `sprite_map'; openbor.o:(.bss+0x8): first defined here
/usr/bin/ld: source/scriptlib/ImportCache.o:(.bss+0x0): multiple definition of `sprite_list'; openbor.o:(.bss+0x0): first defined here
/usr/bin/ld: source/scriptlib/ImportCache.o:(.bss+0x8): multiple definition of `sprite_map'; openbor.o:(.bss+0x8): first defined here
/usr/bin/ld: source/scriptlib/ParserSet.o:(.bss+0x0): multiple definition of `sprite_list'; openbor.o:(.bss+0x0): first defined here
/usr/bin/ld: source/scriptlib/ParserSet.o:(.bss+0x8): multiple definition of `sprite_map'; openbor.o:(.bss+0x8): first defined here
/usr/bin/ld: source/scriptlib/Parser.o:(.bss+0x0): multiple definition of `sprite_list'; openbor.o:(.bss+0x0): first defined here
/usr/bin/ld: source/scriptlib/Parser.o:(.bss+0x8): multiple definition of `sprite_map'; openbor.o:(.bss+0x8): first defined here
/usr/bin/ld: source/scriptlib/Lexer.o:(.bss+0x0): multiple definition of `sprite_list'; openbor.o:(.bss+0x0): first defined here
/usr/bin/ld: source/scriptlib/Lexer.o:(.bss+0x8): multiple definition of `sprite_map'; openbor.o:(.bss+0x8): first defined here
/usr/bin/ld: source/scriptlib/Stack.o:(.bss+0x0): multiple definition of `sprite_list'; openbor.o:(.bss+0x0): first defined here
/usr/bin/ld: source/scriptlib/Stack.o:(.bss+0x8): multiple definition of `sprite_map'; openbor.o:(.bss+0x8): first defined here
/usr/bin/ld: source/scriptlib/List.o:(.bss+0x0): multiple definition of `sprite_list'; openbor.o:(.bss+0x0): first defined here
/usr/bin/ld: source/scriptlib/List.o:(.bss+0x8): multiple definition of `sprite_map'; openbor.o:(.bss+0x8): first defined here
/usr/bin/ld: source/scriptlib/SolidList.o:(.bss+0x0): multiple definition of `sprite_list'; openbor.o:(.bss+0x0): first defined here
/usr/bin/ld: source/scriptlib/SolidList.o:(.bss+0x8): multiple definition of `sprite_map'; openbor.o:(.bss+0x8): first defined here
/usr/bin/ld: source/preprocessorlib/pp_lexer.o:(.bss+0x0): multiple definition of `sprite_list'; openbor.o:(.bss+0x0): first defined here
/usr/bin/ld: source/preprocessorlib/pp_lexer.o:(.bss+0x8): multiple definition of `sprite_map'; openbor.o:(.bss+0x8): first defined here
/usr/bin/ld: source/preprocessorlib/pp_parser.o:(.bss+0x0): multiple definition of `sprite_list'; openbor.o:(.bss+0x0): first defined here
/usr/bin/ld: source/preprocessorlib/pp_parser.o:(.bss+0x8): multiple definition of `sprite_map'; openbor.o:(.bss+0x8): first defined here
/usr/bin/ld: source/preprocessorlib/pp_parser.o:(.bss+0x20): multiple definition of `joysticks'; openbor.o:(.bss+0x20): first defined here
/usr/bin/ld: source/preprocessorlib/pp_parser.o:(.bss+0x4e0): multiple definition of `anim_list'; openbor.o:(.bss+0x4e0): first defined here
/usr/bin/ld: source/preprocessorlib/pp_parser.o:(.bss+0x4e8): multiple definition of `model_cache'; openbor.o:(.bss+0x4e8): first defined here
/usr/bin/ld: source/randlib/rand32.o:(.bss+0x0): multiple definition of `sprite_list'; openbor.o:(.bss+0x0): first defined here
/usr/bin/ld: source/randlib/rand32.o:(.bss+0x8): multiple definition of `sprite_map'; openbor.o:(.bss+0x8): first defined here
/usr/bin/ld: source/pnglib/pngdec.o:(.bss+0x0): multiple definition of `sprite_list'; openbor.o:(.bss+0x0): first defined here
/usr/bin/ld: source/pnglib/pngdec.o:(.bss+0x8): multiple definition of `sprite_map'; openbor.o:(.bss+0x8): first defined here
/usr/bin/ld: source/pnglib/savepng.o:(.bss+0x0): multiple definition of `sprite_list'; openbor.o:(.bss+0x0): first defined here
/usr/bin/ld: source/pnglib/savepng.o:(.bss+0x8): multiple definition of `sprite_map'; openbor.o:(.bss+0x8): first defined here
collect2: error: ld returned 1 exit status
make: *** [Makefile:252: OpenBOR] Error 1
```

**Comment by rofl0r** [comment]
thanks for the log. should be fixed now. you use GCC 10, right ?

**Comment by MrCoolSpan** [comment]
Im at worke right now i check when i get home ;)Sendt fra min Huawei-telefon-------- Oprindelig besked --------Fra: rofl0r <notifications@github.com>Dato: man. d. 8. feb. 2021 07.19Til: rofl0r/openbor <openbor@noreply.github.com>Cc: MrCoolSpan <ribergaard33@gmail.com>, Author <author@noreply.github.com>Emne: Re: [rofl0r/openbor] build on ubuntu 20.04 (#2)
thanks for the log. should be fixed now. you use GCC 10, right ?

**Comment by MrCoolSpan** [comment]
thank you it now works
